### ISSUE TITLE
Datagram endpoint support

### ISSUE THREAD

**Issue by claws** [moonshadow/aiothrift#5]
Are there any plans to support UDP communications? 

I came across this library while trying to create a asyncio compatible client for the Jaeger OpenTracing collector. The collector accepts Thrift binary format trace information by listening on a datagram interface. The existing Python jaeger client is a Python 2.7 library which is not suitable for use in my Python 3 asyncio based applications. 

Would the change roughly be adding a ``create_datagram_endpoint`` function (similar to the existing ``open_connection``) and then creating something like a ThriftDatagram that takes a ``asyncio.DatagramProtocol`` in a similar way to the existing ``ThriftConnection``?

**Comment by ryanwang520** [comment]
Sorry, I'm not familiar with the Jaeger ecosystem, and I think in most cases thrift would use TCP based Transport for reliable communication. Though `asyncio` supports `DatagramProtocol`, A concrete implementation may be related to some specific use case, which I think is not a good idea to implement in  a general library. If you really want to make async thrift work with the `Jaeger ` client,
you can just borrow ideas from this library and try to implement it by yourself. Hope this would help.
